### ISSUE TITLE
Running into issues

### ISSUE THREAD

**Issue by Faiz7412** [jgthms/juketube#14]
I've been trying to run this on aws with nginx on ubuntu. Got lots of errors

**Comment by Faiz7412** [comment]
More on that

```
Faizs-Air:juketube faiz$ node app.js
/Users/faiz/github/party/juketube/app.js:1
(function (exports, require, module, __filename, __dirname) { var app = angular.module('JukeTubeApp', []);
                                                                                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/faiz/github/party/juketube/app.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Faizs-Air:juketube faiz$ 

```

How do I deploy this to AWS on Ubuntu 16.04 running nginx?

**Comment by Faiz7412** [comment]
```
Faizs-Air:juketube faiz$ nano app.js
Faizs-Air:juketube faiz$ sublime .
Faizs-Air:juketube faiz$ nano app.js
Faizs-Air:juketube faiz$ node app.js
/Users/faiz/github/party/juketube/app.js:1
(function (exports, require, module, __filename, __dirname) { var app = angular.module('JukeTubeApp', []);
                                                                                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/faiz/github/party/juketube/app.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Faizs-Air:juketube faiz$ node app.js
/Users/faiz/github/party/juketube/app.js:1
(function (exports, require, module, __filename, __dirname) { var app = angular.module('JukeTubeApp', []);
                                                                                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/faiz/github/party/juketube/app.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Faizs-Air:juketube faiz$ npm install
npm WARN enoent ENOENT: no such file or directory, open '/Users/faiz/package.json'
npm WARN faiz No description
npm WARN faiz No repository field.
npm WARN faiz No README data
npm WARN faiz No license field.
Faizs-Air:juketube faiz$ node app.js
/Users/faiz/github/party/juketube/app.js:1
(function (exports, require, module, __filename, __dirname) { var app = angular.module('JukeTubeApp', []);
                                                                                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/faiz/github/party/juketube/app.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Faizs-Air:juketube faiz$ npm install npm install angular

Faizs-Air:juketube faiz$ npm install angular
/Users/faiz
└── angular@1.6.5 

npm WARN enoent ENOENT: no such file or directory, open '/Users/faiz/package.json'
npm WARN faiz No description
npm WARN faiz No repository field.
npm WARN faiz No README data
npm WARN faiz No license field.
Faizs-Air:juketube faiz$ node app.js
/Users/faiz/github/party/juketube/app.js:1
(function (exports, require, module, __filename, __dirname) { var app = angular.module('JukeTubeApp', []);
                                                                                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/faiz/github/party/juketube/app.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Faizs-Air:juketube faiz$ node app.js
/Users/faiz/github/party/juketube/app.js:1
(function (exports, require, module, __filename, __dirname) { var app = angular.module('JukeTubeApp', []);
                                                                                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/faiz/github/party/juketube/app.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Faizs-Air:juketube faiz$ npm install
npm WARN enoent ENOENT: no such file or directory, open '/Users/faiz/package.json'
npm WARN faiz No description
npm WARN faiz No repository field.
npm WARN faiz No README data
npm WARN faiz No license field.
Faizs-Air:juketube faiz$ npm install
npm WARN enoent ENOENT: no such file or directory, open '/Users/faiz/package.json'
npm WARN faiz No description
npm WARN faiz No repository field.
npm WARN faiz No README data
npm WARN faiz No license field.
Faizs-Air:juketube faiz$ node app.js
/Users/faiz/github/party/juketube/app.js:1
(function (exports, require, module, __filename, __dirname) { var app = angular.module('JukeTubeApp', []);
                                                                                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/faiz/github/party/juketube/app.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
Faizs-Air:juketube faiz$ npm install angular
/Users/faiz
└── angular@1.6.5 

npm WARN enoent ENOENT: no such file or directory, open '/Users/faiz/package.json'
npm WARN faiz No description
npm WARN faiz No repository field.
npm WARN faiz No README data
npm WARN faiz No license field.
Faizs-Air:juketube faiz$ npm app.js

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/faiz/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 /Users/faiz/.nvm/versions/node/v6.11.1/lib/node_modules/npm
Faizs-Air:juketube faiz$ 

```

**Comment by Faiz7412** [comment]
I've already tried installing angular via npm, also did `npm install`  
node app.js or npm app.js doesn't work.

**Comment by CentroEducacional-CEC** [comment]
Apenas extraia na pasta desejada da sua hospedagem e abra o navegador com seu dominio. (https://exemplo.com/jukebox), não tem necessidade de executar comandos!
